name: 'Pull Request Linter'
description: 'Ensures your PR title matches a given regex'
author: 'MorrisonCole'
branding:
  icon: 'check'
  color: 'green'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'