name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: morrisoncole/pr-lint-action@master
      with:
        title-regex: "#EX-[0-9]+"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
