name: pr-lint
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: morrisoncole/pr-lint-action@v0.1.1-alpha
      with:
        title-regex: "#EX-[0-9]+"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
