name: pr-lint
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: morrisoncole/pr-lint-action@v0.1.0-alpha
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
